# Generated by Django 5.2.12 on 2026-04-03 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_reservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.CharField(max_length=2)),
                ('number', models.PositiveSmallIntegerField()),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='movies.hall')),
            ],
            options={
                'ordering': ['hall', 'row', 'number'],
                'constraints': [models.UniqueConstraint(fields=('hall', 'row', 'number'), name='unique_seat_in_hall')],
            },
        ),
    ]
