# Generated by Django 5.2.12 on 2026-04-03 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_seat'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='reserved_seats',
            field=models.ManyToManyField(to='movies.seat'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='hall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.hall'),
        ),
    ]
