<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260515153336 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE training_comment (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, content TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, author_id INT NOT NULL, training_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_494AC262F675F31B ON training_comment (author_id)');
        $this->addSql('CREATE INDEX IDX_494AC262BEFD98D1 ON training_comment (training_id)');
        $this->addSql('ALTER TABLE training_comment ADD CONSTRAINT FK_494AC262F675F31B FOREIGN KEY (author_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE training_comment ADD CONSTRAINT FK_494AC262BEFD98D1 FOREIGN KEY (training_id) REFERENCES training (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE training_comment DROP CONSTRAINT FK_494AC262F675F31B');
        $this->addSql('ALTER TABLE training_comment DROP CONSTRAINT FK_494AC262BEFD98D1');
        $this->addSql('DROP TABLE training_comment');
    }
}
