<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260504171156 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE training_attendance (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, joined_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, participant_id INT NOT NULL, training_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D75DB7F79D1C3019 ON training_attendance (participant_id)');
        $this->addSql('CREATE INDEX IDX_D75DB7F7BEFD98D1 ON training_attendance (training_id)');
        $this->addSql('ALTER TABLE training_attendance ADD CONSTRAINT FK_D75DB7F79D1C3019 FOREIGN KEY (participant_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE training_attendance ADD CONSTRAINT FK_D75DB7F7BEFD98D1 FOREIGN KEY (training_id) REFERENCES training (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE training_attendance DROP CONSTRAINT FK_D75DB7F79D1C3019');
        $this->addSql('ALTER TABLE training_attendance DROP CONSTRAINT FK_D75DB7F7BEFD98D1');
        $this->addSql('DROP TABLE training_attendance');
    }
}
